### ISSUE TITLE
Network Filter crashes on "Get Network" button-click

### ISSUE THREAD

**Issue by tony19** [roryc89/network-filter#4]
Installed this on Chrome Version 49.0.2623.112 (64-bit) on OSX El Capitan. When I click the "Get Network" button, the tab crashes almost immediately:

![screen shot 2016-04-12 at 12 40 23 pm](https://cloud.githubusercontent.com/assets/26580/14469753/d0010d38-00ab-11e6-97df-62c15d302030.png)

Note I had AdBlocker enabled. After disabling it, the behavior changed only slightly in that the console errors (seen in screenshot) were gone, and the tab showed a few rows right before crashing.

Steps to reproduce:
1. Open DevTools, and go to **Network Filter** tab.
2. Navigate to http://google.com.
3. Click the **Get Network** button in the **Network Filter** tab.
4. Observe the **Network Filter** tab shows the "sad document".

**Comment by roryc89** [comment]
@tony19 thanks for the headsup. My latest push has fixed this issue for me when I reproduce your steps. Please let me know if you still have this bug.
